name: aicv
channels:
  - defaults
dependencies:
  - pip:
    - aiofiles==22.1.0
    - aiosqlite==0.18.0
    - anyio==3.6.2
    - appnope==0.1.3
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - attrs==22.2.0
    - babel==2.12.1
    - beautifulsoup4==4.12.0
    - bleach==6.0.0
    - cachetools==5.3.0
    - cffi==1.15.1
    - charset-normalizer==3.1.0
    - comm==0.1.3
    - contourpy==1.0.7
    - cryptography==40.0.2
    - cycler==0.11.0
    - debugpy==1.6.6
    - defusedxml==0.7.1
    - et-xmlfile==1.1.0
    - executing==1.2.0
    - fastjsonschema==2.16.3
    - fonttools==4.39.3
    - fqdn==1.5.1
    - gcloud==0.18.3
    - google-api-core==2.11.0
    - google-api-python-client==2.86.0
    - google-auth==2.17.3
    - google-auth-httplib2==0.1.0
    - google-auth-oauthlib==1.0.0
    - googleapis-common-protos==1.59.0
    - httplib2==0.22.0
    - idna==3.4
    - ipykernel==6.22.0
    - ipython-genutils==0.2.0
    - isoduration==20.11.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - json5==0.9.11
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter-events==0.6.3
    - jupyter-server==2.5.0
    - jupyter-server-fileid==0.8.0
    - jupyter-server-terminals==0.4.4
    - jupyter-server-ydoc==0.8.0
    - jupyter-ydoc==0.2.3
    - jupyterlab==3.6.3
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.22.0
    - kiwisolver==1.4.4
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - mistune==2.0.5
    - nbclassic==0.5.5
    - nbclient==0.7.3
    - nbconvert==7.3.0
    - nbformat==5.8.0
    - notebook==6.5.3
    - notebook-shim==0.2.2
    - numpy==1.24.2
    - oauth2client==4.1.3
    - oauthlib==3.2.2
    - openpyxl==3.1.2
    - pandas==2.0.0
    - pandocfilters==1.5.0
    - pillow==9.5.0
    - platformdirs==3.2.0
    - prometheus-client==0.16.0
    - prompt-toolkit==3.0.38
    - protobuf==4.22.3
    - psutil==5.9.4
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pycparser==2.21
    - pydrive==1.3.1
    - pygments==2.14.0
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - python-json-logger==2.0.7
    - pytz==2023.3
    - pyyaml==6.0
    - pyzmq==25.0.2
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rsa==4.9
    - send2trash==1.8.0
    - sniffio==1.3.0
    - soupsieve==2.4
    - stack-data==0.6.2
    - terminado==0.17.1
    - tinycss2==1.2.1
    - tomli==2.0.1
    - traitlets==5.9.0
    - tzdata==2023.3
    - uri-template==1.2.0
    - uritemplate==4.1.1
    - urllib3==1.26.15
    - vnstock==0.1.4
    - wcwidth==0.2.6
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - y-py==0.5.9
    - ypy-websocket==0.8.2
