desc: "DEFAULT PARAMS CONFIGURATION"
logLevel: 'DEBUG'
dir:
  installedFolder: 
    - database
    - database/drive
    - key
    - key/drive
    - key/drive/tmp
    - report
tokenSetting:
  expiredTime: 3600
dateFormat: '%Y-%m-%d'
datetimeFormat: '%Y-%m-%d %H:%M:%S.%f'