desc: DEFAULT PARAMS CONFIGURATION
logLevel: DEBUG
mode:
  debug:
  release:
remote:
  - name:
security:
  - name:
dir:
  installedFolder: 
    - database
    - database/local
    - database/local/report
    - key
    - key/tmp
dateFormat: '%Y-%m-%d'
datetimeFormat: '%Y-%m-%d %H:%M:%S.%f'