desc: DEVELOPMENT
tokenSetting:
  expiredTime: 10800
remote:
  - name: google_api
    metadata:
      usedServiceEndpoint:
        - drive
      serviceEndpoint:
        - endpoint: drive
          metadata:
            root:
              folderId: 15OcuqE_QvUhO_MOhzeaZKSGprRlwODP2
      credentialSetting:
        tokenExpiredTime: 3600
security:
  - name: tcbs
    metadata:
      audit:
        name: ReviewedData.xlsx
        root: 1d8z3hD6eONCdgPuT6-BHETjy82-nheDh
      remoteServers:
          - name: drive
            root: 1d8z3hD6eONCdgPuT6-BHETjy82-nheDh
            txnHistoryFolder: 19-uZSuya3UUnk9RGWKSy3ExKCYgRd6CY
mode:
  debug:
  release:
