desc: DEVELOPMENT
tokenSetting:
  expiredTime: 10800
remote:
  - name: google_api
    metadata:
      usedServiceEndpoint:
        - drive
      serviceEndpoint:
        - endpoint: drive
          metadata:
            root:
              folderId: 15OcuqE_QvUhO_MOhzeaZKSGprRlwODP2
      credentialSetting:
        tokenExpiredTime: 3600
security:
  - name: tcbs
    metadata:
mode:
  debug:
  release:
