version: 0.0.3
environment: dev
mode: debug
project:
  versionControl: True
  root: /Users/quan/playground/pyaicv
  override: False
loggingFormat: '%(asctime)s - %(levelname)-7s - %(name)-10s : %(message)s'
repo:
  url: git@github.com:HuynhThanhQuan/aicapitalventures.git
  author: Huynh Thanh Quan
  email: hthquan28@gmail.com