desc: "DEBUG MODE"
logLevel: 'DEBUG'
dir:
  root: '/Users/quan/playground/aicv_debug'
  installedFolder: 
    - database
    - database/drive
    - key
    - key/gdrive
    - key/gdrive/tmp
    - report
